"use client";
import React from "react";
import Layout from "./Layout";

const Privacy = () => {
  return (
    <div>
      <Layout title="Privacy Policy">
        <div className="min-h-screen bg-white">
          <style jsx>{`
            body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              margin: 0;
              padding: 20px;
              color: #333;
            }
            h1,
            h2 {
              color: #0056b3;
            }
            h1 {
              text-align: center;
              margin-bottom: 20px;
            }
            h2 {
              margin-top: 30px;
            }
            p,
            ul {
              margin: 10px 0;
            }
            ul {
              padding-left: 20px;
            }
            a {
              color: #0056b3;
              text-decoration: none;
            }
            a:hover {
              text-decoration: underline;
            }
          `}</style>
          <div className="container mx-auto px-6 py-12">
            <div className="prose max-w-none">
              <h1>@Work Privacy Policy</h1>

              <p>
                This document is an electronic record in terms of the
                Information Technology Act, 2000 and rules framed thereunder as
                applicable. This electronic record is generated by a computer
                system and does not require any physical or digital signatures.
              </p>

              <p>
                Tifin India At Work Techsuite Solutions Private Limited,
                operating under its trade name ‘@Work’, (hereinafter referred to
                as “@Work”) is the owner of the website with domain name
                <a href="https://atworkindia.com" target="_blank">
                  https://atworkindia.com
                </a>{" "}
                and the @Work platform (hereinafter referred to as the “@Work
                Platform”).
              </p>

              <p>
                @Work is concerned about the privacy of the Users who access,
                browse, use and transmit content on the @Work Platform. This
                Privacy Policy is for the purpose of acquainting the Users with
                the manner in which @Work collects, uses and discloses the
                Users’ information collected through the @Work Platform.
              </p>
              <h2>Definitions</h2>
              <p>
                For the purposes of this Privacy Policy, the following terms
                shall have the meanings ascribed to them:
              </p>
              <ul>
                <li>
                  <b>We, Us, Our, Company:</b> Refers to Tifin India At Work
                  Techsuite Solutions Private Limited.
                </li>
                <li>
                  <b>You, Yours, Yourself, User, @Work User:</b> Refers to any
                  individual, non-individual, or corporate body.
                </li>
                <li>
                  <b>Cookie:</b> A small text file stored on the User’s computer
                  that will enable @Work to recognize the User when visiting the
                  @Work Platform. It also helps store preferences and settings,
                  enhance experience, perform research and analytics, track
                  activity, and assist with security and administrative
                  functions.
                </li>
                <li>
                  <b>Force Majeure Event:</b> Refers to any event beyond the
                  reasonable control of @Work, including but not limited to
                  sabotage, fire, flood, explosion, acts of God, strikes, riots,
                  war, government actions, computer hacking, and breaches of
                  security.
                </li>
                <li>
                  <b>Personally Identifiable Information:</b> Data or
                  information that personally identifies a User, such as login
                  name, email address, Facebook account details, Google account
                  details, password, and location details, collected during
                  registration on the @Work Platform.
                </li>
                <li>
                  <b>Pixel Tag / Web Beacon / Clear GIF:</b> A tiny graphic with
                  a unique identifier embedded invisibly on a webpage or email.
                  Used to track activity, ad impressions, clicks, and access
                  cookies.
                </li>
                <li>
                  <b>Privacy Policy:</b> Refers to this document.
                </li>
                <li>
                  <b>User(s):</b> Any person accessing or availing the @Work
                  Platform for browsing, viewing, creating, posting, or sharing
                  content.
                </li>
              </ul>
              <h2>General Terms</h2>
              <p>
                The User hereby acknowledges and agrees that the Privacy Policy
                is subject to changes without express and specific intimation.
                Users are required to review the Privacy Policy regularly.
                Continued use of the @Work Platform expresses the User’s consent
                to the updated Privacy Policy.
              </p>
              <p>
                The protection and security of the User’s Personally
                Identifiable Information is one of @Work’s foremost concerns.
                The Privacy Policy discloses @Work’s practices regarding the
                information collected from the User on the @Work Platform.
              </p>
              <p>
                By using the @Work Platform, the User agrees to accept the terms
                of the Privacy Policy as well as @Work’s Terms and Conditions
                available at
                <a href="https://atworkindia.com/terms" target="_blank">
                  https://atworkindia.com/terms
                </a>
                . By accessing or using the @Work Platform, the User expressly
                consents to @Work’s use and disclosure of the User’s personal
                information in the manner described in this Privacy Policy.
              </p>
              <p>
                Users are informed that in accordance with the Information
                Technology (Intermediary Guidelines) Rules, 2011, any
                non-compliance with the Terms & Conditions or the Privacy Policy
                may result in termination of access or usage rights by @Work.
              </p>
              <p>
                The Privacy Policy shall be read along with the Terms &
                Conditions of the @Work Platform. Unless otherwise stated, it
                applies to all information that @Work has about the User and
                their account.
              </p>
              <h2>
                Collection of Personally Identifiable Information and Other
                Information/Data
              </h2>
              <p>
                To access features and benefits of the @Work Platform, Users may
                need to provide certain personal or sensitive information, which
                will be governed under relevant data privacy laws. This
                includes, but is not limited to:
              </p>
              <h3>Onboarding/Registration:</h3>
              <ul>
                <li>
                  Name, DOB, Gender, Nationality, Father’s Name, Mother’s Name,
                  Marital Status, Photo
                </li>
                <li>
                  Address, ZIP/Postal Code, Location, Phone Number, Email ID,
                  Contacts, and Nominee Details
                </li>
                <li>
                  Bank account number, name on bank passbook, and IFSC code
                </li>
                <li>
                  PAN Card Number, Aadhar Card Number (redacted), KYC-related
                  information via online/offline verification for compliance
                  with banking/financial institutions' mandates
                </li>
                <li>
                  Employment-related details (e.g., occupation, income, employer
                  details) for Central KYC Records Registry purposes
                </li>
                <li>
                  Device-related information like communication data (contacts
                  and call logs), camera/microphone access, storage, device
                  type, IP address, and location for location-based services and
                  security.
                </li>
              </ul>
              <h3>KYC Details:</h3>
              <p>
                To comply with regulatory requirements, explicit consent is
                taken to fetch KYC details from regulated KYC registries such as
                CKYC, CVL, etc.
              </p>

              <h3>Credit Score and Liabilities Information:</h3>
              <ul>
                <li>
                  Explicit consent is taken to collect credit-related
                  information from third-party service providers like Experian
                  or CRIF High Mark.
                </li>
                <li>
                  Access to email accounts may be requested to analyze credit
                  card account details, financial transactions, curated rewards,
                  and offers.
                </li>
              </ul>

              <h3>Investment Information:</h3>
              <ul>
                <li>
                  Users may upload investment statements in PDF or Excel
                  formats, or allow @Work to fetch these from third-party
                  providers like depositories or brokers.
                </li>
                <li>
                  Investment details such as scheme name, type, date, and value
                  can also be manually entered.
                </li>
              </ul>

              <h3>Email Accounts:</h3>
              <p>
                Users can choose to integrate email accounts to auto-track
                investments and financial data. Only read-only access is
                provided, and explicit consent is required for this integration.
                Users can de-link their email accounts or delete information by
                writing to
                <a href="mailto:account.deletion@atworkindia.com">
                  account.deletion@atworkindia.com
                </a>
                .
              </p>
              <p>
                The information collected will solely be used to provide
                services and improve the user experience.
              </p>
              <h2>Tracking of Information</h2>
              <p>
                @Work may use Cookies, Pixel Tags, Web Beacons, flash cookies,
                and similar technologies to collect, track, and store
                information based on the User’s activity on the @Work Platform.
                For example:
              </p>
              <ul>
                <li>
                  Pixel Tags: Used to measure the popularity of pages, people,
                  or hashtags.
                </li>
                <li>
                  Web Beacons: Embedded in emails or newsletters to determine
                  whether the message has been opened and to collect analytics.
                </li>
              </ul>
              <p>
                Most browsers allow Cookies by default. Users can modify their
                browser settings to block specific Cookies, but this may
                interfere with certain functionalities of the @Work Platform.
                Flash cookies cannot be removed or blocked through web browser
                settings.
              </p>
              <p>
                By using the @Work Platform, Users consent to the use of Cookies
                and similar technologies as described in this section.
              </p>
              <p>
                Note: @Work has no control over third-party Cookies used on the
                platform.
              </p>
              <h2>Collection and Use of Non-Personal Data</h2>
              <p>
                Non-personal data is information that cannot identify an
                individual. @Work may collect such data to monitor customer
                activities and improve services. Examples include:
              </p>
              <ul>
                <li>Aggregated customer activity information</li>
                <li>Browser text files</li>
              </ul>
              <p>
                This data may be shared in an aggregated, non-personal form with
                third parties to enhance customer experience, offerings, or
                services.
              </p>
              <h2>Sharing of Information</h2>
              <p>
                @Work may use User information to verify identity, contact
                Users, or provide platform services. Information sharing
                scenarios include:
              </p>
              <ul>
                <li>
                  <b>Business Restructuring:</b> If @Work merges with or is
                  acquired by another entity, User information may be shared.
                </li>
                <li>
                  <b>Government Compliance:</b> Personally Identifiable
                  Information may be shared with government agencies for fraud
                  prevention, detection, and investigation.
                </li>
                <li>
                  <b>Legal Obligations:</b> Information may be disclosed in
                  compliance with court orders or other legal requirements.
                </li>
              </ul>
              <p>
                @Work will only share Personally Identifiable Information in
                compliance with this Privacy Policy.
              </p>
              <h2>Assessing, Reviewing, and Changing Personal Information</h2>
              <p>
                @Work will take reasonable steps to accurately record the
                personal information provided by the User and any subsequent
                updates. Users are encouraged to review, update, and correct
                their information through the @Work Platform.
              </p>
              <p>
                Upon request, @Work will delete any inaccurate, incomplete, or
                irrelevant information that infringes applicable legal
                requirements. However, there may be circumstances where
                corrections or deletions are not possible, including:
              </p>
              <ul>
                <li>
                  When the data is opinion-based and kept solely for evaluative
                  purposes.
                </li>
                <li>
                  When the data is in documents related to prosecution where
                  proceedings have not been completed.
                </li>
              </ul>
              <p>
                Users wishing to cancel their accounts or request data deletion
                can contact @Work via the contact information provided below.
              </p>
              <h2>Retention Period</h2>
              <p>
                @Work does not retain personal data longer than necessary for
                the purpose of processing, except where required by applicable
                laws, including but not limited to:
              </p>
              <ul>
                <li>
                  Securities and Exchange Board of India (Investment Advisers)
                  Regulations, 2013
                </li>
                <li>
                  Insurance Regulatory Development Authority of India
                  (Registration of Corporate Agents) Regulations, 2015
                </li>
                <li>Prevention of Money Laundering Act, 2002</li>
              </ul>
              <p>
                Retained data may be used to satisfy legal, regulatory, or
                accounting requirements, or for the defense of legal claims.
                Data may also be aggregated and anonymized for research or
                statistical purposes, in which case it can be used indefinitely.
              </p>
              <p>
                Upon account deletion, all associated data will be removed
                within 90 days, except for data required by law. Users can
                request data deletion via the @Work mobile application or by
                contacting
                <a href="mailto:account.deletion@atworkindia.com">
                  account.deletion@atworkindia.com
                </a>
                .
              </p>
              <h2>Retention Period</h2>
              <p>
                @Work does not retain personal data longer than necessary for
                the purpose of processing, except where required by applicable
                laws, including but not limited to:
              </p>
              <ul>
                <li>
                  Securities and Exchange Board of India (Investment Advisers)
                  Regulations, 2013
                </li>
                <li>
                  Insurance Regulatory Development Authority of India
                  (Registration of Corporate Agents) Regulations, 2015
                </li>
                <li>Prevention of Money Laundering Act, 2002</li>
              </ul>
              <p>
                Retained data may be used to satisfy legal, regulatory, or
                accounting requirements, or for the defense of legal claims.
                Data may also be aggregated and anonymized for research or
                statistical purposes, in which case it can be used indefinitely.
              </p>
              <p>
                Upon account deletion, all associated data will be removed
                within 90 days, except for data required by law. Users can
                request data deletion via the @Work mobile application or by
                contacting
                <a href="mailto:account.deletion@atworkindia.com">
                  account.deletion@atworkindia.com
                </a>
                .
              </p>
              <h2>Security Precautions</h2>
              <p>
                @Work has implemented physical, electronic, and managerial
                procedures to safeguard User information and maintain data
                security. These measures consider the sensitivity of the
                information and the current state of technology.
              </p>
              <p>
                While @Work follows generally accepted industry standards to
                protect User data, no method of transmission over the internet
                is 100% secure. Therefore, @Work cannot guarantee absolute
                security.
              </p>
              <p>
                Users play an important role in securing their information and
                are advised not to share account credentials with anyone.
                Instructions received through the User’s account and password
                will be considered authorized.
              </p>
              <p>
                @Work assumes no liability for disclosure of User information
                caused by errors in transmission, unauthorized access, or other
                causes beyond its control. Additionally, @Work will not be
                responsible for any loss, damage, or misuse of data due to Force
                Majeure Events.
              </p>
              <h2>Changes to the Privacy Policy</h2>
              <p>
                @Work reserves the right to amend this Privacy Policy from time
                to time to reflect changes in applicable laws, data collection
                practices, platform features, or advances in technology. Users
                are encouraged to check this page periodically for updates.
              </p>
              <p>
                Use of information collected by @Work will be subject to the
                Privacy Policy in effect at the time such information is used.
                If material changes are made to this Privacy Policy, @Work will
                post the updates on the platform. Continued use of the platform
                following these updates will constitute the User's consent and
                acceptance of the changes.
              </p>
              <h2>Governing Law & Dispute</h2>
              <p>
                The laws governing this Privacy Policy shall be the substantive
                laws of the Republic of India, without regard to its conflicts
                of law principles.
              </p>
              <p>
                Any disputes arising out of or in connection with this Privacy
                Policy shall be referred to and resolved through arbitration. A
                sole arbitrator, appointed by @Work, will conduct the
                arbitration in accordance with the Arbitration Rules of the
                Mumbai Centre for International Arbitration (MCIA). The seat and
                venue of arbitration shall be Bangalore, India.
              </p>
              <h2>Disclaimer of Information</h2>
              <p>
                @Work does not control or endorse content, messages, or
                information placed on its platform by Users or third parties.
                Therefore, @Work specifically disclaims any liability related to
                such content, messages, or interactions.
              </p>
              <p>
                Users are responsible for maintaining the accuracy,
                truthfulness, and completeness of the information they provide
                on the platform. Incorrect or false information may result in
                claims, for which the User shall indemnify and hold @Work
                harmless.
              </p>
              <p>
                If the User wishes to correct, delete, or amend information, or
                if they wish to cancel their account, they may contact @Work
                using the provided contact details. However, there may be
                circumstances where corrections or deletions are not possible,
                such as:
              </p>
              <ul>
                <li>
                  When the data is opinion-based and kept solely for evaluative
                  purposes.
                </li>
                <li>
                  When the data is part of documents related to prosecution
                  where proceedings have not been completed.
                </li>
              </ul>

              <h2>Grievance Officer</h2>
              <p>
                In accordance with the provisions of the Information Technology
                Act, 2000, and rules made thereunder, the details of the
                Grievance Officer are provided below:
              </p>
              <p>
                <b>Attn:</b> Mr. Deepak Malani
                <br />
                <b>Designation:</b> Grievance Officer
                <br />
                <b>Email:</b>{" "}
                <a href="mailto:grievance@atworkindia.com">
                  grievance@atworkindia.com
                </a>
                <br />
                <b>Time:</b> Mon - Friday (10 AM - 7 PM)
                <br />
                <b>Address:</b> 3H/54 Pearl, Kalpataru Aura, Phase II, LBS Marg,
                Ghatkopar West, Mumbai, 400086, Maharashtra
              </p>
              <p style={{ textAlign: "center", marginTop: "40px" }}>
                <i>Last updated on 20th Dec 2024</i>
              </p>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Privacy;
